/**
 * DISCOVERY CANDIDATES — well-known companies on each supported ATS, used by
 * `bun run discover` to verify live before anything is seeded.
 *
 * This is the FALLBACK candidate list (the shared /home/team/shared/
 * ats-candidates.md is read when present and merged with this). Every entry is
 * a guess to be VERIFIED live — nothing here is seeded until the board API
 * returns HTTP 200 with at least one job. Wrong guesses simply land in the
 * honest failure report (http-404 / http-429 / robots-blocked / parse-error)
 * and are never seeded.
 *
 * Workable is deliberately absent (re-verified live 2026-08-15): the widget
 * API returns clean HTTP 404s for unknown accounts and no bot challenge
 * reproduces, but no REAL Workable account has been obtained/verified yet —
 * so no Workable row exists for discovery to probe. A real subdomain (from a
 * user check of an apply.workable.com URL, or a curated add) would flow
 * through the normal verify path (the fetcher is implemented and tested).
 */

import type { BoardKind } from "./boards";

export interface DiscoveryCandidate {
  /** Public company display name (becomes the `company` field on postings). */
  name: string;
  board: BoardKind;
  /** Board-native id: Greenhouse boardToken, Ashby org, Lever company slug. */
  boardId: string;
  /** Optional public careers URL (surfaced on the company profile when known). */
  careerUrl?: string;
}

/** (board, boardId) key used for dedupe and state tracking. */
export function candidateKey(c: DiscoveryCandidate): string {
  return `${c.board}:${c.boardId.toLowerCase()}`;
}

const G: Omit<DiscoveryCandidate, "board">[] = [
  { name: "Stripe", boardId: "stripe", careerUrl: "https://stripe.com/jobs" },
  { name: "Airbnb", boardId: "airbnb", careerUrl: "https://careers.airbnb.com" },
  { name: "Instacart", boardId: "instacart", careerUrl: "https://instacart.careers" },
  { name: "Datadog", boardId: "datadog", careerUrl: "https://www.datadoghq.com/careers" },
  { name: "Okta", boardId: "okta", careerUrl: "https://www.okta.com/company/careers" },
  { name: "Twilio", boardId: "twilio", careerUrl: "https://www.twilio.com/company/jobs" },
  { name: "Dropbox", boardId: "dropbox", careerUrl: "https://www.dropbox.com/jobs" },
  { name: "Pinterest", boardId: "pinterest", careerUrl: "https://www.pinterestcareers.com" },
  { name: "Lyft", boardId: "lyft", careerUrl: "https://www.lyft.com/careers" },
  { name: "Coinbase", boardId: "coinbase", careerUrl: "https://www.coinbase.com/careers" },
  { name: "Reddit", boardId: "reddit", careerUrl: "https://www.redditinc.com/careers" },
  { name: "Roblox", boardId: "roblox", careerUrl: "https://careers.roblox.com" },
  { name: "Duolingo", boardId: "duolingo", careerUrl: "https://careers.duolingo.com" },
  { name: "Grammarly", boardId: "grammarly", careerUrl: "https://www.grammarly.com/jobs" },
  { name: "Monzo", boardId: "monzo", careerUrl: "https://monzo.com/careers" },
  { name: "Wise", boardId: "wise", careerUrl: "https://www.wise.jobs" },
  { name: "Klarna", boardId: "klarna", careerUrl: "https://www.klarna.com/careers" },
  { name: "Nubank", boardId: "nubank", careerUrl: "https://nubank.com.br/careers" },
  { name: "Shopify", boardId: "shopify", careerUrl: "https://www.shopify.com/careers" },
  { name: "Zillow", boardId: "zillow", careerUrl: "https://www.zillow.com/careers" },
  { name: "Wayfair", boardId: "wayfair", careerUrl: "https://www.wayfair.com/careers" },
  { name: "Deliveroo", boardId: "deliveroo", careerUrl: "https://careers.deliveroo.co.uk" },
  { name: "DoorDash", boardId: "doordash", careerUrl: "https://careersatdoordash.com" },
  { name: "Figma", boardId: "figma", careerUrl: "https://www.figma.com/careers" },
  { name: "Asana", boardId: "asana", careerUrl: "https://asana.com/jobs" },
  { name: "Gusto", boardId: "gusto", careerUrl: "https://gusto.com/about/careers" },
  { name: "Webflow", boardId: "webflow", careerUrl: "https://webflow.com/careers" },
  { name: "Vercel", boardId: "vercel", careerUrl: "https://vercel.com/careers" },
  { name: "MongoDB", boardId: "mongodb", careerUrl: "https://www.mongodb.com/careers" },
  { name: "Elastic", boardId: "elastic", careerUrl: "https://www.elastic.co/careers" },
  { name: "Databricks", boardId: "databricks", careerUrl: "https://www.databricks.com/company/careers" },
  { name: "Confluent", boardId: "confluent", careerUrl: "https://www.confluent.io/careers" },
  { name: "GitLab", boardId: "gitlab", careerUrl: "https://about.gitlab.com/jobs" },
  { name: "CrowdStrike", boardId: "crowdstrike", careerUrl: "https://www.crowdstrike.com/careers" },
  { name: "HubSpot", boardId: "hubspot", careerUrl: "https://www.hubspot.com/careers" },
  { name: "Brex", boardId: "brex", careerUrl: "https://www.brex.com/careers" },
  { name: "Rippling", boardId: "rippling", careerUrl: "https://www.rippling.com/careers" },
  { name: "NerdWallet", boardId: "nerdwallet", careerUrl: "https://www.nerdwallet.com/careers" },
  { name: "Warby Parker", boardId: "warbyparker", careerUrl: "https://www.warbyparker.com/careers" },
  { name: "Allbirds", boardId: "allbirds", careerUrl: "https://www.allbirds.com/pages/careers" },
  { name: "Scale AI", boardId: "scale", careerUrl: "https://scale.com/careers" },
  { name: "OpenAI", boardId: "openai", careerUrl: "https://openai.com/careers" },
  { name: "Anthropic", boardId: "anthropic", careerUrl: "https://www.anthropic.com/careers" },
  { name: "Zapier", boardId: "zapier", careerUrl: "https://zapier.com/jobs" },
  { name: "Amplitude", boardId: "amplitude", careerUrl: "https://amplitude.com/careers" },
  { name: "Mixpanel", boardId: "mixpanel", careerUrl: "https://mixpanel.com/careers" },
  { name: "Postman", boardId: "postman", careerUrl: "https://www.postman.com/company/careers" },
  { name: "ClickUp", boardId: "clickup", careerUrl: "https://clickup.com/careers" },
  { name: "Expensify", boardId: "expensify", careerUrl: "https://we.are.expensify.com" },
  { name: "Netlify", boardId: "netlify", careerUrl: "https://www.netlify.com/careers" },
  { name: "Grafana Labs", boardId: "grafana", careerUrl: "https://grafana.com/careers" },
  { name: "HashiCorp", boardId: "hashicorp", careerUrl: "https://www.hashicorp.com/careers" },
  { name: "Cockroach Labs", boardId: "cockroachlabs", careerUrl: "https://www.cockroachlabs.com/careers" },
  { name: "Snyk", boardId: "snyk", careerUrl: "https://snyk.io/careers" },
  { name: "Sentry", boardId: "sentry", careerUrl: "https://sentry.io/careers" },
  { name: "Cloudflare", boardId: "cloudflare", careerUrl: "https://www.cloudflare.com/careers" },
  { name: "Fastly", boardId: "fastly", careerUrl: "https://www.fastly.com/careers" },
  { name: "Affirm", boardId: "affirm", careerUrl: "https://www.affirm.com/careers" },
  { name: "Chime", boardId: "chime", careerUrl: "https://www.chime.com/careers" },
  { name: "SoFi", boardId: "sofi", careerUrl: "https://www.sofi.com/careers" },
  { name: "Robinhood", boardId: "robinhood", careerUrl: "https://careers.robinhood.com" },
  { name: "Deel", boardId: "deel", careerUrl: "https://www.deel.com/careers" },
  { name: "Remote", boardId: "remote", careerUrl: "https://remote.com/careers" },
  { name: "Automattic", boardId: "automattic", careerUrl: "https://automattic.com/work-with-us" },
  { name: "Airtable", boardId: "airtable", careerUrl: "https://www.airtable.com/careers" },
  { name: "Discord", boardId: "discord", careerUrl: "https://discord.com/careers" },
  { name: "Kraken", boardId: "kraken", careerUrl: "https://www.kraken.com/careers" },
  { name: "Circle", boardId: "circle", careerUrl: "https://www.circle.com/careers" },
  { name: "N26", boardId: "n26", careerUrl: "https://n26.com/en/careers" },
  { name: "Pleo", boardId: "pleo", careerUrl: "https://www.pleo.io/careers" },
  { name: "Klaviyo", boardId: "klaviyo", careerUrl: "https://www.klaviyo.com/careers" },
  { name: "Braze", boardId: "braze", careerUrl: "https://www.braze.com/careers" },
  { name: "Block", boardId: "block", careerUrl: "https://block.xyz/careers" },
  { name: "Squarespace", boardId: "squarespace", careerUrl: "https://www.squarespace.com/careers" },
  { name: "GoDaddy", boardId: "godaddy", careerUrl: "https://careers.godaddy.com" },
  { name: "Toast", boardId: "toast", careerUrl: "https://careers.toasttab.com" },
  { name: "Wikimedia", boardId: "wikimedia", careerUrl: "https://wikimediafoundation.org/about/jobs" },
  { name: "Mozilla", boardId: "mozilla", careerUrl: "https://www.mozilla.org/careers" },
  { name: "DuckDuckGo", boardId: "duckduckgo", careerUrl: "https://duckduckgo.com/careers" },
  { name: "Brave", boardId: "brave", careerUrl: "https://brave.com/careers" },
  { name: "Wealthfront", boardId: "wealthfront", careerUrl: "https://www.wealthfront.com/careers" },
  { name: "Betterment", boardId: "betterment", careerUrl: "https://www.betterment.com/careers" },
  { name: "Acorns", boardId: "acorns", careerUrl: "https://acorns.com/careers" },
  { name: "Varo", boardId: "varo", careerUrl: "https://www.varo.com/careers" },
  { name: "Greenlight", boardId: "greenlight", careerUrl: "https://greenlight.com/careers" },
  { name: "Drata", boardId: "drata", careerUrl: "https://drata.com/careers" },
  { name: "Vanta", boardId: "vanta", careerUrl: "https://www.vanta.com/careers" },
  { name: "Anysphere", boardId: "anysphere", careerUrl: "https://cursor.com/careers" },
  { name: "Runway", boardId: "runway", careerUrl: "https://runwayml.com/careers" },
  { name: "PlanetScale", boardId: "planetscale", careerUrl: "https://planetscale.com/careers" },
  { name: "Palantir", boardId: "palantir", careerUrl: "https://www.palantir.com/careers" },
  { name: "Quora", boardId: "quora", careerUrl: "https://www.quora.com/careers" },
  { name: "Whoop", boardId: "whoop", careerUrl: "https://www.whoop.com/careers" },
  { name: "Tonal", boardId: "tonal", careerUrl: "https://www.tonal.com/careers" },
  { name: "Casper", boardId: "casper", careerUrl: "https://casper.com/careers" },
  { name: "Brooklinen", boardId: "brooklinen", careerUrl: "https://www.brooklinen.com/careers" },
  { name: "Burrow", boardId: "burrow", careerUrl: "https://burrow.com/careers" },
  { name: "Outdoor Voices", boardId: "outdoorvoices", careerUrl: "https://www.outdoorvoices.com/careers" },
  { name: "Revolut", boardId: "revolut", careerUrl: "https://www.revolut.com/careers" },
  { name: "Spendesk", boardId: "spendesk", careerUrl: "https://www.spendesk.com/careers" },
  { name: "PayFit", boardId: "payfit", careerUrl: "https://payfit.com/careers" },
  { name: "Alan", boardId: "alan", careerUrl: "https://alan.com/careers" },
  { name: "Drift", boardId: "drift", careerUrl: "https://www.drift.com/careers" },
  { name: "Segment", boardId: "segment", careerUrl: "https://segment.com/careers" },
];

const A: Omit<DiscoveryCandidate, "board">[] = [
  { name: "Airbnb", boardId: "airbnb", careerUrl: "https://careers.airbnb.com" },
  { name: "Linear", boardId: "linear", careerUrl: "https://linear.app/careers" },
  { name: "Mercury", boardId: "mercury", careerUrl: "https://mercury.com/careers" },
  { name: "Ramp", boardId: "ramp", careerUrl: "https://ramp.com/careers" },
  { name: "Retool", boardId: "retool", careerUrl: "https://retool.com/careers" },
  { name: "Coda", boardId: "coda", careerUrl: "https://coda.io/careers" },
  { name: "Framer", boardId: "framer", careerUrl: "https://www.framer.com/careers" },
  { name: "Raycast", boardId: "raycast", careerUrl: "https://www.raycast.com/careers" },
  { name: "Superhuman", boardId: "superhuman", careerUrl: "https://superhuman.com/careers" },
  { name: "The Browser Company", boardId: "arc", careerUrl: "https://thebrowser.company/careers" },
  { name: "Finch", boardId: "finch", careerUrl: "https://finch.com/careers" },
  { name: "Ironclad", boardId: "ironclad", careerUrl: "https://ironcladapp.com/careers" },
  { name: "Tines", boardId: "tines", careerUrl: "https://www.tines.com/careers" },
  { name: "Teleport", boardId: "teleport", careerUrl: "https://goteleport.com/careers" },
  { name: "Hasura", boardId: "hasura", careerUrl: "https://hasura.io/careers" },
  { name: "Apollo", boardId: "apollo", careerUrl: "https://www.apollo.io/careers" },
  { name: "Hex", boardId: "hex", careerUrl: "https://hex.tech/careers" },
  { name: "Wiz", boardId: "wiz", careerUrl: "https://www.wiz.io/careers" },
  { name: "Midjourney", boardId: "midjourney", careerUrl: "https://www.midjourney.com/careers" },
  { name: "Arize AI", boardId: "arize", careerUrl: "https://arize.com/careers" },
  { name: "Weaviate", boardId: "weaviate", careerUrl: "https://weaviate.io/careers" },
  { name: "Pinecone", boardId: "pinecone", careerUrl: "https://www.pinecone.io/careers" },
  { name: "Kalshi", boardId: "kalshi", careerUrl: "https://kalshi.com/careers" },
  { name: "Parafin", boardId: "parafin", careerUrl: "https://www.parafin.com/careers" },
  { name: "Replit", boardId: "replit", careerUrl: "https://replit.com/careers" },
  { name: "ElevenLabs", boardId: "elevenlabs", careerUrl: "https://elevenlabs.io/careers" },
  { name: "Hugging Face", boardId: "huggingface", careerUrl: "https://huggingface.co/careers" },
  { name: "Mistral AI", boardId: "mistral", careerUrl: "https://mistral.ai/careers" },
  { name: "Perplexity", boardId: "perplexity", careerUrl: "https://www.perplexity.ai/careers" },
  { name: "Loom", boardId: "loom", careerUrl: "https://www.loom.com/careers" },
  { name: "Descript", boardId: "descript", careerUrl: "https://www.descript.com/careers" },
  { name: "dbt Labs", boardId: "dbt", careerUrl: "https://www.getdbt.com/careers" },
  { name: "Resend", boardId: "resend", careerUrl: "https://resend.com/careers" },
  { name: "Supabase", boardId: "supabase", careerUrl: "https://supabase.com/careers" },
  { name: "Render", boardId: "render", careerUrl: "https://render.com/careers" },
  { name: "PostHog", boardId: "posthog", careerUrl: "https://posthog.com/careers" },
  { name: "Tailscale", boardId: "tailscale", careerUrl: "https://tailscale.com/careers" },
  { name: "1Password", boardId: "1password", careerUrl: "https://1password.com/careers" },
  { name: "Airbyte", boardId: "airbyte", careerUrl: "https://airbyte.com/careers" },
  { name: "Sourcegraph", boardId: "sourcegraph", careerUrl: "https://sourcegraph.com/careers" },
  { name: "Snowflake", boardId: "snowflake", careerUrl: "https://www.snowflake.com/careers" },
  { name: "CommandBar", boardId: "commandbar", careerUrl: "https://www.commandbar.com/careers" },
  { name: "Trumid", boardId: "trumid", careerUrl: "https://www.trumid.com/careers" },
  { name: "Abridge", boardId: "abridge", careerUrl: "https://www.abridge.com/careers" },
  { name: "Replicate", boardId: "replicate", careerUrl: "https://replicate.com/careers" },
  { name: "Weights & Biases", boardId: "wandb", careerUrl: "https://wandb.ai/careers" },
  { name: "Modal", boardId: "modal", careerUrl: "https://modal.com/careers" },
  { name: "Baseten", boardId: "baseten", careerUrl: "https://www.baseten.co/careers" },
  { name: "Together AI", boardId: "together", careerUrl: "https://www.together.ai/careers" },
  { name: "Glean", boardId: "glean", careerUrl: "https://www.glean.com/careers" },
  { name: "Hebbia", boardId: "hebbia", careerUrl: "https://www.hebbia.ai/careers" },
  { name: "Astranis", boardId: "astranis", careerUrl: "https://www.astranis.com/careers" },
  { name: "Knock", boardId: "knock", careerUrl: "https://knock.app/careers" },
  { name: "Infinite Campus", boardId: "infinitecampus", careerUrl: "https://www.infinitecampus.com/careers" },
];

const L: Omit<DiscoveryCandidate, "board">[] = [
  { name: "Spotify", boardId: "spotify", careerUrl: "https://www.lifeatspotify.com" },
  { name: "Vimeo", boardId: "vimeo", careerUrl: "https://www.vimeo.com/jobs" },
  { name: "Yelp", boardId: "yelp", careerUrl: "https://www.yelpcareers.com" },
  { name: "Coursera", boardId: "coursera", careerUrl: "https://www.coursera.org/careers" },
  { name: "Udemy", boardId: "udemy", careerUrl: "https://about.udemy.com/careers" },
  { name: "Canva", boardId: "canva", careerUrl: "https://www.canva.com/careers" },
  { name: "Dandy", boardId: "dandy", careerUrl: "https://www.dandy.com/careers" },
  { name: "Ro", boardId: "ro", careerUrl: "https://ro.co/careers" },
  { name: "Calm", boardId: "calm", careerUrl: "https://www.calm.com/careers" },
  { name: "Headspace", boardId: "headspace", careerUrl: "https://www.headspace.com/careers" },
  { name: "MasterClass", boardId: "masterclass", careerUrl: "https://www.masterclass.com/careers" },
  { name: "Gong", boardId: "gong", careerUrl: "https://www.gong.io/careers" },
  { name: "Outreach", boardId: "outreach", careerUrl: "https://www.outreach.io/careers" },
  { name: "6sense", boardId: "6sense", careerUrl: "https://6sense.com/careers" },
  { name: "Mux", boardId: "mux", careerUrl: "https://www.mux.com/careers" },
  { name: "Cloudinary", boardId: "cloudinary", careerUrl: "https://cloudinary.com/careers" },
  { name: "Algolia", boardId: "algolia", careerUrl: "https://www.algolia.com/careers" },
  { name: "Contentful", boardId: "contentful", careerUrl: "https://www.contentful.com/careers" },
  { name: "Unity", boardId: "unity", careerUrl: "https://careers.unity.com" },
  { name: "Benchling", boardId: "benchling", careerUrl: "https://www.benchling.com/careers" },
  { name: "Bill.com", boardId: "bill", careerUrl: "https://www.bill.com/careers" },
  { name: "Procore", boardId: "procore", careerUrl: "https://www.procore.com/careers" },
  { name: "SentinelOne", boardId: "sentinelone", careerUrl: "https://www.sentinelone.com/careers" },
  { name: "Darktrace", boardId: "darktrace", careerUrl: "https://darktrace.com/careers" },
  { name: "Cohere", boardId: "cohere", careerUrl: "https://cohere.com/careers" },
  { name: "Jasper", boardId: "jasper", careerUrl: "https://www.jasper.ai/careers" },
  { name: "Writer", boardId: "writer", careerUrl: "https://writer.com/careers" },
  { name: "Whop", boardId: "whop", careerUrl: "https://whop.com/careers" },
  { name: "Fivetran", boardId: "fivetran", careerUrl: "https://www.fivetran.com/careers" },
  { name: "Intercom", boardId: "intercom", careerUrl: "https://www.intercom.com/careers" },
  { name: "Typeform", boardId: "typeform", careerUrl: "https://www.typeform.com/careers" },
  { name: "BigCommerce", boardId: "bigcommerce", careerUrl: "https://www.bigcommerce.com/careers" },
  { name: "Rover", boardId: "rover", careerUrl: "https://www.rover.com/careers" },
  { name: "Gemini", boardId: "gemini", careerUrl: "https://www.gemini.com/careers" },
  { name: "Netskope", boardId: "netskope", careerUrl: "https://www.netskope.com/careers" },
  { name: "Lucid Software", boardId: "lucid", careerUrl: "https://lucid.co/careers" },
  { name: "Hims & Hers", boardId: "hims", careerUrl: "https://www.hims.com/careers" },
  { name: "Babbel", boardId: "babbel", careerUrl: "https://www.babbel.com/careers" },
  { name: "Wefox", boardId: "wefox", careerUrl: "https://www.wefox.com/careers" },
  { name: "Getir", boardId: "getir", careerUrl: "https://getir.com/careers" },
  { name: "Gopuff", boardId: "gopuff", careerUrl: "https://gopuff.com/careers" },
  { name: "Kustomer", boardId: "kustomer", careerUrl: "https://www.kustomer.com/careers" },
  { name: "Front", boardId: "front", careerUrl: "https://front.com/careers" },
  { name: "Lob", boardId: "lob", careerUrl: "https://www.lob.com/careers" },
  { name: "WalkMe", boardId: "walkme", careerUrl: "https://www.walkme.com/careers" },
  { name: "Affinity", boardId: "affinity", careerUrl: "https://www.affinity.co/careers" },
  { name: "Aircall", boardId: "aircall", careerUrl: "https://aircall.io/careers" },
  { name: "Volley", boardId: "volley", careerUrl: "https://www.volleythat.com/careers" },
  { name: "Zocdoc", boardId: "zocdoc", careerUrl: "https://www.zocdoc.com/careers" },
  { name: "Tempus", boardId: "tempus", careerUrl: "https://www.tempus.com/careers" },
  { name: "10x Genomics", boardId: "10xgenomics", careerUrl: "https://www.10xgenomics.com/careers" },
  { name: "Invitae", boardId: "invitae", careerUrl: "https://www.invitae.com/careers" },
  { name: "Deezer", boardId: "deezer", careerUrl: "https://www.deezer.com/careers" },
  { name: "SoundCloud", boardId: "soundcloud", careerUrl: "https://soundcloud.com/careers" },
  { name: "Dialpad", boardId: "dialpad", careerUrl: "https://www.dialpad.com/careers" },
  { name: "MessageBird", boardId: "messagebird", careerUrl: "https://messagebird.com/careers" },
  { name: "Sendbird", boardId: "sendbird", careerUrl: "https://sendbird.com/careers" },
  { name: "Stream", boardId: "stream", careerUrl: "https://getstream.io/careers" },
  { name: "Courier", boardId: "courier", careerUrl: "https://www.courier.com/careers" },
  { name: "Customer.io", boardId: "customerio", careerUrl: "https://customer.io/careers" },
  { name: "Appcues", boardId: "appcues", careerUrl: "https://www.appcues.com/careers" },
  { name: "Pendo", boardId: "pendo", careerUrl: "https://www.pendo.io/careers" },
  { name: "Gainsight", boardId: "gainsight", careerUrl: "https://www.gainsight.com/careers" },
  { name: "ChurnZero", boardId: "churnzero", careerUrl: "https://churnzero.com/careers" },
  { name: "Mode", boardId: "mode", careerUrl: "https://mode.com/careers" },
  { name: "Metabase", boardId: "metabase", careerUrl: "https://www.metabase.com/careers" },
  { name: "Sisense", boardId: "sisense", careerUrl: "https://www.sisense.com/careers" },
  { name: "Sigma", boardId: "sigma", careerUrl: "https://www.sigmacomputing.com/careers" },
  { name: "Deepnote", boardId: "deepnote", careerUrl: "https://deepnote.com/careers" },
  { name: "Strava", boardId: "strava", careerUrl: "https://www.strava.com/careers" },
  { name: "Peloton", boardId: "peloton", careerUrl: "https://www.onepeloton.com/careers" },
  { name: "Oura", boardId: "oura", careerUrl: "https://ouraring.com/careers" },
  { name: "Zwift", boardId: "zwift", careerUrl: "https://zwift.com/careers" },
];

export const FALLBACK_CANDIDATES: DiscoveryCandidate[] = [
  ...G.map((c) => ({ ...c, board: "greenhouse" as BoardKind })),
  ...A.map((c) => ({ ...c, board: "ashby" as BoardKind })),
  ...L.map((c) => ({ ...c, board: "lever" as BoardKind })),
];
