/**
 * Curated company→industry classification (our taxonomy, labeled as our classification on
 * public pages — ATS APIs do not provide industry). Verify-by-eyeball welcome; wrong rows
 * are cheap to fix.
 *
 * Honesty note: this is OUR curated single-label-per-company classification, not a
 * market-standard industry taxonomy (SIC/NAICS/etc.). It is a best-effort mapping of each
 * company's PRIMARY business for the monthly report's "industries hiring the most jobs"
 * breakdown. Ambiguous companies were assigned the closest-fit bucket; genuinely uncertain
 * ones are flagged in the UNCERTAIN list in the PR that adds this file.
 */
export const COMPANY_INDUSTRIES: Record<string, string> = {
  "1password": "Cybersecurity",
  "10x genomics": "Healthcare/Biotech",
  "23andme": "Healthcare/Biotech",
  "6sense": "Marketing/AdTech",
  "abridge": "Healthcare/Biotech",
  "acorns": "Fintech",
  "affinity": "Marketing/AdTech",
  "affirm": "Fintech",
  "aircall": "Software/Internet",
  "airbyte": "Developer Tools/Infrastructure",
  "airbnb": "Travel",
  "airtable": "Software/Internet",
  "alan": "Healthcare/Biotech",
  "algolia": "Developer Tools/Infrastructure",
  "allbirds": "E-commerce/Retail",
  "amplitude": "Software/Internet",
  "anduril": "Defense/Aerospace",
  "anthropic": "AI/ML",
  "anyscale": "AI/ML",
  "anysphere": "Developer Tools/Infrastructure",
  "apartment list": "Real Estate/PropTech",
  "apollo": "Marketing/AdTech",
  "appcues": "Software/Internet",
  "applied intuition": "AI/ML",
  "arize ai": "AI/ML",
  "asana": "Software/Internet",
  "assemblyai": "AI/ML",
  "astranis": "Defense/Aerospace",
  "auth0": "Cybersecurity",
  "automattic": "Software/Internet",
  "babbel": "Edtech",
  "bark": "E-commerce/Retail",
  "baseten": "AI/ML",
  "benchling": "Healthcare/Biotech",
  "better.com": "Fintech",
  "betterment": "Fintech",
  "bigcommerce": "E-commerce/Retail",
  "bill.com": "Fintech",
  "blend": "Fintech",
  "block": "Fintech",
  "borrowell": "Fintech",
  "box": "Software/Internet",
  "brave": "Software/Internet",
  "braze": "Marketing/AdTech",
  "brex": "Fintech",
  "brooklinen": "E-commerce/Retail",
  "burrow": "E-commerce/Retail",
  "busbud": "Travel",
  "calendly": "Software/Internet",
  "calm": "Consumer Apps",
  "canva": "Software/Internet",
  "captions": "AI/ML",
  "carta": "Fintech",
  "casper": "E-commerce/Retail",
  "chainalysis": "Crypto/Web3",
  "character.ai": "AI/ML",
  "chewy": "E-commerce/Retail",
  "chili piper": "Marketing/AdTech",
  "chime": "Fintech",
  "churnzero": "Software/Internet",
  "circle": "Crypto/Web3",
  "circleci": "Developer Tools/Infrastructure",
  "classpass": "Consumer Apps",
  "clickup": "Software/Internet",
  "cloudflare": "Developer Tools/Infrastructure",
  "cloudinary": "Developer Tools/Infrastructure",
  "cockroach labs": "Developer Tools/Infrastructure",
  "coda": "Software/Internet",
  "codecademy": "Edtech",
  "cohere": "AI/ML",
  "coinbase": "Crypto/Web3",
  "commandbar": "Developer Tools/Infrastructure",
  "confluent": "Developer Tools/Infrastructure",
  "contentful": "Developer Tools/Infrastructure",
  "copy.ai": "AI/ML",
  "courier": "Developer Tools/Infrastructure",
  "coursera": "Edtech",
  "crowdstrike": "Cybersecurity",
  "customer.io": "Marketing/AdTech",
  "dandy": "Healthcare/Biotech",
  "darktrace": "Cybersecurity",
  "databricks": "AI/ML",
  "datadog": "Developer Tools/Infrastructure",
  "dbt labs": "Developer Tools/Infrastructure",
  "deezer": "Media/Content",
  "deel": "HR/Recruiting",
  "deepgram": "AI/ML",
  "deepnote": "Developer Tools/Infrastructure",
  "deliveroo": "Logistics/Supply Chain",
  "descript": "Media/Content",
  "dialpad": "Software/Internet",
  "digitalocean": "Developer Tools/Infrastructure",
  "discord": "Consumer Apps",
  "docker": "Developer Tools/Infrastructure",
  "doordash": "Logistics/Supply Chain",
  "drata": "Cybersecurity",
  "drift": "Marketing/AdTech",
  "dropbox": "Software/Internet",
  "duckduckgo": "Software/Internet",
  "duolingo": "Edtech",
  "elastic": "Developer Tools/Infrastructure",
  "elevenlabs": "AI/ML",
  "employ": "HR/Recruiting",
  "etsy": "E-commerce/Retail",
  "eventbrite": "Consumer Apps",
  "expensify": "Fintech",
  "faire": "E-commerce/Retail",
  "fastly": "Developer Tools/Infrastructure",
  "figma": "Software/Internet",
  "finch": "HR/Recruiting",
  "fireworks ai": "AI/ML",
  "fivetran": "Developer Tools/Infrastructure",
  "framer": "Software/Internet",
  "front": "Software/Internet",
  "gainsight": "Software/Internet",
  "gemini": "Crypto/Web3",
  "getir": "Logistics/Supply Chain",
  "gitlab": "Developer Tools/Infrastructure",
  "glean": "AI/ML",
  "glossier": "E-commerce/Retail",
  "godaddy": "Software/Internet",
  "gofundme": "Consumer Apps",
  "gong": "Marketing/AdTech",
  "gopuff": "Logistics/Supply Chain",
  "grafana labs": "Developer Tools/Infrastructure",
  "grammarly": "AI/ML",
  "greenhouse": "HR/Recruiting",
  "greenlight": "Fintech",
  "groq": "AI/ML",
  "guild education": "Edtech",
  "gusto": "HR/Recruiting",
  "handshake": "HR/Recruiting",
  "harness": "Developer Tools/Infrastructure",
  "hashicorp": "Developer Tools/Infrastructure",
  "hasura": "Developer Tools/Infrastructure",
  "headspace": "Consumer Apps",
  "headway": "Healthcare/Biotech",
  "hebbia": "AI/ML",
  "hex": "Developer Tools/Infrastructure",
  "heygen": "AI/ML",
  "highlevel": "Marketing/AdTech",
  "hims & hers": "Healthcare/Biotech",
  "homelight": "Real Estate/PropTech",
  "hootsuite": "Marketing/AdTech",
  "hubspot": "Marketing/AdTech",
  "hugging face": "AI/ML",
  "ideogram": "AI/ML",
  "infinite campus": "Edtech",
  "instacart": "Logistics/Supply Chain",
  "intercom": "Software/Internet",
  "invitae": "Healthcare/Biotech",
  "ironclad": "Software/Internet",
  "iterable": "Marketing/AdTech",
  "jasper": "AI/ML",
  "kalshi": "Fintech",
  "khan academy": "Edtech",
  "klarna": "Fintech",
  "klaviyo": "Marketing/AdTech",
  "knock": "Developer Tools/Infrastructure",
  "kraken": "Crypto/Web3",
  "kustomer": "Software/Internet",
  "league": "Healthcare/Biotech",
  "ledger": "Crypto/Web3",
  "lemonade": "Fintech",
  "lever": "HR/Recruiting",
  "linear": "Software/Internet",
  "lob": "Developer Tools/Infrastructure",
  "loom": "Software/Internet",
  "lucid software": "Software/Internet",
  "luma ai": "AI/ML",
  "lyft": "Logistics/Supply Chain",
  "masterclass": "Edtech",
  "mercury": "Fintech",
  "messagebird": "Software/Internet",
  "metabase": "Developer Tools/Infrastructure",
  "midjourney": "AI/ML",
  "mindbody": "Consumer Apps",
  "mistral ai": "AI/ML",
  "mixpanel": "Software/Internet",
  "modal": "AI/ML",
  "mode": "Developer Tools/Infrastructure",
  "mongodb": "Developer Tools/Infrastructure",
  "monzo": "Fintech",
  "moonpay": "Crypto/Web3",
  "mozilla": "Software/Internet",
  "mux": "Developer Tools/Infrastructure",
  "n26": "Fintech",
  "neon": "Developer Tools/Infrastructure",
  "nerdwallet": "Fintech",
  "netskope": "Cybersecurity",
  "netlify": "Developer Tools/Infrastructure",
  "new relic": "Developer Tools/Infrastructure",
  "nextdoor": "Consumer Apps",
  "noom": "Consumer Apps",
  "notion": "Software/Internet",
  "nubank": "Fintech",
  "okta": "Cybersecurity",
  "opendoor": "Real Estate/PropTech",
  "openai": "AI/ML",
  "opensea": "Crypto/Web3",
  "opusclip": "AI/ML",
  "oscar health": "Healthcare/Biotech",
  "oura": "Consumer Apps",
  "outdoor voices": "E-commerce/Retail",
  "outreach": "Marketing/AdTech",
  "oyster": "HR/Recruiting",
  "pagerduty": "Developer Tools/Infrastructure",
  "palantir": "Software/Internet",
  "parafin": "Fintech",
  "patreon": "Media/Content",
  "payfit": "HR/Recruiting",
  "peloton": "Consumer Apps",
  "pendo": "Software/Internet",
  "perplexity": "AI/ML",
  "pika": "AI/ML",
  "pinecone": "AI/ML",
  "pinterest": "Consumer Apps",
  "plaid": "Fintech",
  "planetscale": "Developer Tools/Infrastructure",
  "pleo": "Fintech",
  "posthog": "Developer Tools/Infrastructure",
  "postman": "Developer Tools/Infrastructure",
  "procore": "Software/Internet",
  "public.com": "Fintech",
  "quora": "Media/Content",
  "quizlet": "Edtech",
  "ramp": "Fintech",
  "raycast": "Developer Tools/Infrastructure",
  "reddit": "Consumer Apps",
  "redfin": "Real Estate/PropTech",
  "remote": "HR/Recruiting",
  "render": "Developer Tools/Infrastructure",
  "replicate": "AI/ML",
  "replit": "Developer Tools/Infrastructure",
  "resend": "Developer Tools/Infrastructure",
  "retool": "Developer Tools/Infrastructure",
  "revolut": "Fintech",
  "rippling": "HR/Recruiting",
  "ro": "Healthcare/Biotech",
  "robinhood": "Fintech",
  "roblox": "Gaming",
  "rover": "Consumer Apps",
  "runway": "AI/ML",
  "sanity": "Developer Tools/Infrastructure",
  "scale ai": "AI/ML",
  "seatgeek": "Consumer Apps",
  "segment": "Marketing/AdTech",
  "sendbird": "Developer Tools/Infrastructure",
  "sentinelone": "Cybersecurity",
  "sentry": "Developer Tools/Infrastructure",
  "servicetitan": "Software/Internet",
  "shopify": "E-commerce/Retail",
  "sigma": "Developer Tools/Infrastructure",
  "sisense": "Developer Tools/Infrastructure",
  "snyk": "Cybersecurity",
  "snowflake": "Developer Tools/Infrastructure",
  "sofi": "Fintech",
  "soundcloud": "Media/Content",
  "sourcegraph": "Developer Tools/Infrastructure",
  "spendesk": "Fintech",
  "spotify": "Media/Content",
  "spring health": "Healthcare/Biotech",
  "squarespace": "Software/Internet",
  "stability ai": "AI/ML",
  "stack overflow": "Media/Content",
  "strava": "Consumer Apps",
  "stream": "Developer Tools/Infrastructure",
  "stripe": "Fintech",
  "substack": "Media/Content",
  "suno": "AI/ML",
  "superhuman": "Software/Internet",
  "supabase": "Developer Tools/Infrastructure",
  "synthesia": "AI/ML",
  "tailscale": "Developer Tools/Infrastructure",
  "teleport": "Cybersecurity",
  "tempus": "Healthcare/Biotech",
  "the browser company": "Software/Internet",
  "thrive market": "E-commerce/Retail",
  "thumbtack": "Consumer Apps",
  "tines": "Cybersecurity",
  "toast": "Software/Internet",
  "together ai": "AI/ML",
  "tonal": "Consumer Apps",
  "touchbistro": "Software/Internet",
  "trumid": "Fintech",
  "turo": "Travel",
  "twilio": "Software/Internet",
  "typeform": "Software/Internet",
  "udemy": "Edtech",
  "uipath": "Software/Internet",
  "uniswap labs": "Crypto/Web3",
  "unity": "Gaming",
  "vanta": "Cybersecurity",
  "varo": "Fintech",
  "veed": "Media/Content",
  "veo": "Other",
  "vercel": "Developer Tools/Infrastructure",
  "vimeo": "Media/Content",
  "vidyard": "Marketing/AdTech",
  "volley": "Gaming",
  "walkme": "Software/Internet",
  "warby parker": "E-commerce/Retail",
  "wave": "Fintech",
  "wayfair": "E-commerce/Retail",
  "wealthfront": "Fintech",
  "wealthsimple": "Fintech",
  "weaviate": "AI/ML",
  "webflow": "Software/Internet",
  "wefox": "Fintech",
  "weights & biases": "AI/ML",
  "whop": "E-commerce/Retail",
  "whoop": "Consumer Apps",
  "wiz": "Cybersecurity",
  "wikimedia": "Media/Content",
  "wise": "Fintech",
  "writer": "AI/ML",
  "yelp": "Consumer Apps",
  "you.com": "AI/ML",
  "zapier": "Software/Internet",
  "zendesk": "Software/Internet",
  "zillow": "Real Estate/PropTech",
  "zocdoc": "Healthcare/Biotech",
  "zwift": "Consumer Apps",
};

/** Companies not in the curated map: keep them countable, never drop them. */
export const FALLBACK_INDUSTRY = "Unclassified";
export function industryForCompany(name: string): string {
  const key = name.trim().toLowerCase();
  return COMPANY_INDUSTRIES[key] ?? FALLBACK_INDUSTRY;
}
