/**
 * COMPANY REGISTRY — the monitored-company list the sync loop scrubs.
 *
 * A monitored company is a record:
 *
 *   { name, boards: [{ board: "greenhouse"|"ashby"|"lever"|"workable",
 *                      boardId: <token/subdomain/org> }], careerUrl? }
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * HOW TO ADD A COMPANY (keep it real, keep it verified)
 * ─────────────────────────────────────────────────────────────────────────────
 * 1. Confirm the company actually runs a board on one of the supported ATSes
 *    (their careers page will link to boards.greenhouse.io/<token>,
 *    jobs.ashbyhq.com/<org>, jobs.lever.co/<org> or apply.workable.com/<sub>).
 * 2. VERIFY THE ENDPOINT LIVE before adding — it must return HTTP 200 plus a
 *    non-empty job list:
 *      Greenhouse: https://boards-api.greenhouse.io/v1/boards/<token>/jobs
 *      Ashby:      https://api.ashbyhq.com/posting-api/job-board/<org>
 *      Lever:      https://api.lever.co/v0/postings/<org>?mode=json
 *      Workable:   https://apply.workable.com/api/v1/widget/accounts/<sub>/jobs
 *    (Workable currently returns HTTP 429 bot-challenge — see note below.)
 * 3. Add an entry to SEED_COMPANIES with the exact public company name (this
 *    name becomes the `company` field on ingested postings, which is what the
 *    identity/removal logic keys on).
 *
 * SCALED REGISTRY: since 2026-08-14 the seed list is generated by the
 * discovery pipeline (`bun run discover`, engine/discover.ts) — candidates
 * are verified live against each board API and only HTTP-200-with-jobs
 * companies are emitted to engine/verified-companies.ts and merged here
 * (deduped by normalized name; a company verified on a second ATS gets the
 * extra board appended). The original five seeds (Greenhouse, Notion,
 * HighLevel, Veo, Employ) remain in the merge so the registry never shrinks.
 * Re-run `bun run discover` to grow the registry; re-running the sync picks
 * the new companies up automatically. Full per-candidate hit/failure reports
 * land in engine/data/discovery-report-*.txt.
 *
 * WORKABLE STATUS (verified 2026-08-14): apply.workable.com serves a bot
 * challenge (HTTP 429, even for /robots.txt), so no Workable account can be
 * verified or seeded today. The client exists in boards.ts and returns the 429
 * as a structured error; auto-discovery still registers Workable companies
 * from user-tracked URLs, and each sync reports the per-board failure honestly.
 */

import type { Store } from "./store";
import type { BoardKind } from "./boards";
import type { PostingRecord } from "./types";
import { VERIFIED_COMPANIES } from "./verified-companies";

export interface CompanyBoardRef {
  board: BoardKind;
  /** Board-native id: Greenhouse boardToken, Ashby org, Lever company slug, Workable subdomain. */
  boardId: string;
}

export interface MonitoredCompany {
  /** Public company name — becomes the `company` field on ingested postings. */
  name: string;
  boards: CompanyBoardRef[];
  careerUrl?: string;
  /** When this entry was verified live (ISO date). */
  verifiedAt?: string;
}

/** The original verified-by-hand seeds — kept so the registry never shrinks. */
const LEGACY_SEEDS: MonitoredCompany[] = [
  {
    name: "Greenhouse",
    boards: [{ board: "greenhouse", boardId: "greenhouse" }],
    careerUrl: "https://www.greenhouse.io/careers",
    verifiedAt: "2026-08-14",
  },
  {
    name: "Notion",
    boards: [{ board: "ashby", boardId: "notion" }],
    careerUrl: "https://www.notion.so/careers",
    verifiedAt: "2026-08-14",
  },
  {
    name: "HighLevel",
    boards: [{ board: "lever", boardId: "gohighlevel" }],
    careerUrl: "https://www.gohighlevel.com/careers",
    verifiedAt: "2026-08-14",
  },
  {
    name: "Veo",
    boards: [{ board: "lever", boardId: "veo" }],
    careerUrl: "https://veo.co/careers",
    verifiedAt: "2026-08-14",
  },
  {
    name: "Employ",
    boards: [{ board: "lever", boardId: "employ" }],
    careerUrl: "https://www.employinc.com/careers",
    verifiedAt: "2026-08-14",
  },
];

/**
 * Merge verified companies with the legacy seeds: dedupe by normalized name,
 * append extra boards when a company verifies on a second ATS. Deterministic
 * (sorted by name) so the sync cursor stays stable across deploys.
 */
export function mergeSeedCompanies(verified: MonitoredCompany[]): MonitoredCompany[] {
  const byKey = new Map<string, MonitoredCompany>();
  const normKey = (name: string) => name.trim().toLowerCase();
  const add = (c: MonitoredCompany) => {
    const key = normKey(c.name);
    const existing = byKey.get(key);
    if (!existing) {
      byKey.set(key, { ...c, boards: [...c.boards] });
      return;
    }
    for (const b of c.boards) {
      if (!existing.boards.some((x) => x.board === b.board && x.boardId === b.boardId)) {
        existing.boards.push(b);
      }
    }
    if (c.careerUrl && !existing.careerUrl) existing.careerUrl = c.careerUrl;
  };
  for (const c of [...LEGACY_SEEDS, ...verified]) add(c);
  return [...byKey.values()].sort((a, b) => a.name.localeCompare(b.name));
}

/** Verified-live seed list (see header for the verification procedure). */
export const SEED_COMPANIES: MonitoredCompany[] = mergeSeedCompanies(VERIFIED_COMPANIES);

/** Hosts that are actually ATS board pages (not marketing sites). */
const BOARD_HOSTS: Record<string, BoardKind> = {
  "boards.greenhouse.io": "greenhouse",
  "job-boards.greenhouse.io": "greenhouse",
  "jobs.ashbyhq.com": "ashby",
  "jobs.lever.co": "lever",
  "apply.workable.com": "workable",
};

const LOOPBACK_HOSTS = new Set(["127.0.0.1", "localhost", "::1", "[::1]"]);

function isLoopbackUrl(url: string): boolean {
  try {
    const host = new URL(url).hostname.toLowerCase();
    return LOOPBACK_HOSTS.has(host) || host.endsWith(".localhost");
  } catch {
    return false;
  }
}

/**
 * Derive the board + boardId a posting URL belongs to, when it is hosted on a
 * board we can scrub. Returns null for non-board URLs (incl. loopback fixtures).
 *
 *   boards.greenhouse.io/{token}/jobs/{id}  → greenhouse/{token}
 *   jobs.ashbyhq.com/{org}/{uuid}           → ashby/{org}
 *   jobs.lever.co/{org}/{uuid}              → lever/{org}
 *   apply.workable.com/{sub}/p/{shortcode}  → workable/{sub}
 */
export function boardRefFromUrl(url: string): CompanyBoardRef | null {
  if (isLoopbackUrl(url)) return null;
  try {
    const u = new URL(url);
    const host = u.hostname.toLowerCase();
    const board = BOARD_HOSTS[host];
    if (!board) return null;
    const seg = u.pathname.split("/").filter(Boolean);
    const boardId = seg[0] ?? null;
    if (!boardId) return null;
    return { board, boardId: decodeURIComponent(boardId) };
  } catch {
    return null;
  }
}

/**
 * AUTO-DISCOVERY FROM EXISTING DATA — the registry is the seed list PLUS every
 * company we can derive from postings already in the store whose canonical URL
 * is hosted on a supported board (i.e. postings users have checked). New
 * companies are upserted/deduped by normalized name; a company found on a
 * second board gets the extra board appended. Pure function of the store —
 * nothing is persisted (the scheduling layer can persist later if needed).
 */
export async function buildRegistry(store: Store, records?: PostingRecord[]): Promise<MonitoredCompany[]> {
  const byKey = new Map<string, MonitoredCompany>();
  const normKey = (name: string) => name.trim().toLowerCase();

  for (const c of SEED_COMPANIES) {
    byKey.set(normKey(c.name), { ...c, boards: [...c.boards] });
  }

  for (const r of records ?? (await store.getAll())) {
    if (!r.canonicalUrl) continue;
    const ref = boardRefFromUrl(r.canonicalUrl);
    if (!ref) continue;
    const name = r.company?.trim() || ref.boardId;
    const key = normKey(name);
    const existing = byKey.get(key);
    if (existing) {
      if (!existing.boards.some((b) => b.board === ref.board && b.boardId === ref.boardId)) {
        existing.boards.push(ref);
      }
    } else {
      byKey.set(key, { name, boards: [ref] });
    }
  }

  return [...byKey.values()].sort((a, b) => a.name.localeCompare(b.name));
}
