/**
 * COMPANY REGISTRY — the monitored-company list the sync loop scrubs.
 *
 * A monitored company is a record:
 *
 *   { name, boards: [{ board: "greenhouse"|"ashby"|"lever"|"workable",
 *                      boardId: <token/subdomain/org> }], careerUrl? }
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * HOW TO ADD A COMPANY (keep it real, keep it verified)
 * ─────────────────────────────────────────────────────────────────────────────
 * 1. Confirm the company actually runs a board on one of the supported ATSes
 *    (their careers page will link to boards.greenhouse.io/<token>,
 *    jobs.ashbyhq.com/<org>, jobs.lever.co/<org> or apply.workable.com/<sub>).
 * 2. VERIFY THE ENDPOINT LIVE before adding — it must return HTTP 200 plus a
 *    non-empty job list:
 *      Greenhouse: https://boards-api.greenhouse.io/v1/boards/<token>/jobs
 *      Ashby:      https://api.ashbyhq.com/posting-api/job-board/<org>
 *      Lever:      https://api.lever.co/v0/postings/<org>?mode=json
 *      Workable:   https://apply.workable.com/api/v1/widget/accounts/<sub>/jobs
 *    (Workable currently returns HTTP 429 bot-challenge — see note below.)
 * 3. Add an entry to SEED_COMPANIES with the exact public company name (this
 *    name becomes the `company` field on ingested postings, which is what the
 *    identity/removal logic keys on).
 *
 * SCALED REGISTRY: since 2026-08-14 the seed list is generated by the
 * discovery pipeline (`bun run discover`, engine/discover.ts) — candidates
 * are verified live against each board API and only HTTP-200-with-jobs
 * companies are emitted to engine/verified-companies.ts and merged here
 * (deduped by normalized name; a company verified on a second ATS gets the
 * extra board appended). The original five seeds (Greenhouse, Notion,
 * HighLevel, Veo, Employ) remain in the merge so the registry never shrinks.
 * Re-run `bun run discover` to grow the registry; re-running the sync picks
 * the new companies up automatically. Full per-candidate hit/failure reports
 * land in engine/data/discovery-report-*.txt.
 *
 * SCHEDULED GROWTH (owner direction 2026-08-15, design: registry-growth-design.md):
 * buildRegistry merges THREE sources, deduped by normalized name:
 *   1. SEED_COMPANIES (the verified-live seed list above),
 *   2. `discovery_candidates WHERE status='verified'` (the Neon pool —
 *      seeded by `bun run seed-candidates`, fed continuously by user checks
 *      and verified daily by the 01:45 UTC `/api/cron/discover` pass), and
 *   3. every company derivable from postings already in the store.
 * The Neon pool is the single source of truth for growth; the TS seed list
 * remains the bootstrap for a fresh DB. Test-fixture names/boardIds
 * (TestCo/acme) are denylisted so test artifacts can never enter the
 * registry (see TEST_ARTIFACT below).
 *
 * WORKABLE STATUS (re-verified live 2026-08-15): apply.workable.com's
 * robots.txt fetches fine (no rules → allowed) and the widget API returns
 * clean HTTP 404s for unknown accounts — NO bot challenge reproduced on 10
 * probed subdomains. Workable still has 0 accounts in the registry for an
 * honest reason: no candidate, seed, or user check has ever produced a real
 * Workable board ref, so nothing probes a valid account. The client exists in
 * boards.ts and would work if a real subdomain were registered; until then,
 * Workable boards report 0 accounts and are labeled as our observed sample.
 */

import type { Store } from "./store";
import type { BoardKind } from "./boards";
import type { PostingRecord } from "./types";
import { VERIFIED_COMPANIES } from "./verified-companies";

export interface CompanyBoardRef {
  board: BoardKind;
  /** Board-native id: Greenhouse boardToken, Ashby org, Lever company slug, Workable subdomain. */
  boardId: string;
}

export interface MonitoredCompany {
  /** Public company name — becomes the `company` field on ingested postings. */
  name: string;
  boards: CompanyBoardRef[];
  careerUrl?: string;
  /** When this entry was verified live (ISO date). */
  verifiedAt?: string;
}

/** The original verified-by-hand seeds — kept so the registry never shrinks. */
const LEGACY_SEEDS: MonitoredCompany[] = [
  {
    name: "Greenhouse",
    boards: [{ board: "greenhouse", boardId: "greenhouse" }],
    careerUrl: "https://www.greenhouse.io/careers",
    verifiedAt: "2026-08-14",
  },
  {
    name: "Notion",
    boards: [{ board: "ashby", boardId: "notion" }],
    careerUrl: "https://www.notion.so/careers",
    verifiedAt: "2026-08-14",
  },
  {
    name: "HighLevel",
    boards: [{ board: "lever", boardId: "gohighlevel" }],
    careerUrl: "https://www.gohighlevel.com/careers",
    verifiedAt: "2026-08-14",
  },
  {
    name: "Veo",
    boards: [{ board: "lever", boardId: "veo" }],
    careerUrl: "https://veo.co/careers",
    verifiedAt: "2026-08-14",
  },
  {
    name: "Employ",
    boards: [{ board: "lever", boardId: "employ" }],
    careerUrl: "https://www.employinc.com/careers",
    verifiedAt: "2026-08-14",
  },
];

/**
 * Merge verified companies with the legacy seeds: dedupe by normalized name,
 * append extra boards when a company verifies on a second ATS. Deterministic
 * (sorted by name) so the sync cursor stays stable across deploys.
 */
export function mergeSeedCompanies(verified: MonitoredCompany[]): MonitoredCompany[] {
  const byKey = new Map<string, MonitoredCompany>();
  const normKey = (name: string) => name.trim().toLowerCase();
  const add = (c: MonitoredCompany) => {
    const key = normKey(c.name);
    const existing = byKey.get(key);
    if (!existing) {
      byKey.set(key, { ...c, boards: [...c.boards] });
      return;
    }
    for (const b of c.boards) {
      if (!existing.boards.some((x) => x.board === b.board && x.boardId === b.boardId)) {
        existing.boards.push(b);
      }
    }
    if (c.careerUrl && !existing.careerUrl) existing.careerUrl = c.careerUrl;
  };
  for (const c of [...LEGACY_SEEDS, ...verified]) add(c);
  return [...byKey.values()].sort((a, b) => a.name.localeCompare(b.name));
}

/** Verified-live seed list (see header for the verification procedure). */
export const SEED_COMPANIES: MonitoredCompany[] = mergeSeedCompanies(VERIFIED_COMPANIES);

/** Hosts that are actually ATS board pages (not marketing sites). */
const BOARD_HOSTS: Record<string, BoardKind> = {
  "boards.greenhouse.io": "greenhouse",
  "job-boards.greenhouse.io": "greenhouse",
  "jobs.ashbyhq.com": "ashby",
  "jobs.lever.co": "lever",
  "apply.workable.com": "workable",
};

const LOOPBACK_HOSTS = new Set(["127.0.0.1", "localhost", "::1", "[::1]"]);

function isLoopbackUrl(url: string): boolean {
  try {
    const host = new URL(url).hostname.toLowerCase();
    return LOOPBACK_HOSTS.has(host) || host.endsWith(".localhost");
  } catch {
    return false;
  }
}

/**
 * TEST-ARTIFACT DENYLIST (design §4.4) — test suites (watchlist-test.ts and
 * friends) write real-shaped fixture postings into the LIVE Neon store
 * (company "TestCo", URLs under boards.greenhouse.io/acme/jobs/fx-…). Without
 * a guard those fixtures auto-discover a phantom registry company that 404s
 * on every sync cycle (the live "TestCo" phantom, purged 2026-08-15). Applied
 * in buildRegistry (postings-derived merge) AND in
 * Store.ensureDiscoveryCandidateFromPosting (/check hook), so fixtures can
 * never re-enter the registry or the discovery pool. Long-term fix (noted):
 * run fixture-writing tests against a scratch Neon database.
 */
export const TEST_ARTIFACT = {
  /** Fixture company names ("TestCo", "SyncTestCo", ...). */
  companyRe: /test/i,
  /** Fixture board ids used by the watchlist/sync fixture postings. */
  boardIds: new Set(["acme"]),
} as const;

/** True when a company name looks like a test-fixture name. */
export function isTestArtifactName(name: string): boolean {
  return TEST_ARTIFACT.companyRe.test(name.trim());
}

/** True when a board id is a known test-fixture board. */
export function isTestArtifactBoardId(boardId: string): boolean {
  return TEST_ARTIFACT.boardIds.has(boardId.trim().toLowerCase());
}

/**
 * Derive the board + boardId a posting URL belongs to, when it is hosted on a
 * board we can scrub. Returns null for non-board URLs (incl. loopback fixtures).
 *
 *   boards.greenhouse.io/{token}/jobs/{id}  → greenhouse/{token}
 *   jobs.ashbyhq.com/{org}/{uuid}           → ashby/{org}
 *   jobs.lever.co/{org}/{uuid}              → lever/{org}
 *   apply.workable.com/{sub}/p/{shortcode}  → workable/{sub}
 */
export function boardRefFromUrl(url: string): CompanyBoardRef | null {
  if (isLoopbackUrl(url)) return null;
  try {
    const u = new URL(url);
    const host = u.hostname.toLowerCase();
    const board = BOARD_HOSTS[host];
    if (!board) return null;
    const seg = u.pathname.split("/").filter(Boolean);
    const boardId = seg[0] ?? null;
    if (!boardId) return null;
    return { board, boardId: decodeURIComponent(boardId) };
  } catch {
    return null;
  }
}

/**
 * AUTO-DISCOVERY FROM EXISTING DATA — the registry is the seed list PLUS every
 * company we can derive from postings already in the store whose canonical URL
 * is hosted on a supported board (i.e. postings users have checked). New
 * companies are upserted/deduped by normalized name; a company found on a
 * second board gets the extra board appended. Pure function of the store —
 * nothing is persisted (the scheduling layer can persist later if needed).
 *
 * SCHEDULED GROWTH MERGE (owner direction 2026-08-15): verified rows from the
 * Neon discovery_candidates pool join the merge (source of truth for growth —
 * a company verified by the daily 01:45 UTC discovery pass joins the registry
 * here with its verifiedAt, ahead of its first board sync). Test-artifact
 * fixture names/boardIds are excluded (see TEST_ARTIFACT). Deterministic
 * (sorted) so the sync cursor stays stable across deploys.
 */
export async function buildRegistry(store: Store, records?: PostingRecord[]): Promise<MonitoredCompany[]> {
  const byKey = new Map<string, MonitoredCompany>();
  const normKey = (name: string) => name.trim().toLowerCase();
  const add = (c: MonitoredCompany) => {
    const key = normKey(c.name);
    const existing = byKey.get(key);
    if (!existing) {
      byKey.set(key, { ...c, boards: [...c.boards] });
      return;
    }
    for (const b of c.boards) {
      if (!existing.boards.some((x) => x.board === b.board && x.boardId === b.boardId)) {
        existing.boards.push(b);
      }
    }
    if (c.careerUrl && !existing.careerUrl) existing.careerUrl = c.careerUrl;
    if (c.verifiedAt && !existing.verifiedAt) existing.verifiedAt = c.verifiedAt;
  };

  for (const c of SEED_COMPANIES) add(c);

  for (const c of await store.listVerifiedDiscoveryCandidates()) {
    if (isTestArtifactName(c.name) || isTestArtifactBoardId(c.boardId)) continue;
    add({
      name: c.name,
      boards: [{ board: c.board, boardId: c.boardId }],
      ...(c.careerUrl ? { careerUrl: c.careerUrl } : {}),
      ...(c.verifiedAt ? { verifiedAt: c.verifiedAt } : {}),
    });
  }

  for (const r of records ?? (await store.getAll())) {
    if (!r.canonicalUrl) continue;
    const ref = boardRefFromUrl(r.canonicalUrl);
    if (!ref) continue;
    const name = r.company?.trim() || ref.boardId;
    if (isTestArtifactName(name) || isTestArtifactBoardId(ref.boardId)) continue;
    add({ name, boards: [ref] });
  }

  return [...byKey.values()].sort((a, b) => a.name.localeCompare(b.name));
}
