/**
 * VERIFIED COMPANIES — generated by `bun run discover` (engine/discover.ts).
 * DO NOT EDIT BY HAND: re-run discovery to regenerate. Only companies that
 * returned HTTP 200 with at least one job are listed here — everything else is
 * reported in engine/data/discovery-report-*.txt and never seeded.
 * Merged into SEED_COMPANIES (engine/companies.ts) by normalized name.
 * Generated 2026-08-14T16:25:10.908Z.
 */
import type { MonitoredCompany } from "./companies";

export const VERIFIED_COMPANIES: MonitoredCompany[] = [
  {
    name: "1Password",
    careerUrl: "https://1password.com/careers",
    boards: [
    { board: "ashby", boardId: "1password" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Abridge",
    careerUrl: "https://www.abridge.com/careers",
    boards: [
    { board: "ashby", boardId: "abridge" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Affirm",
    careerUrl: "https://www.affirm.com/careers",
    boards: [
    { board: "greenhouse", boardId: "affirm" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Airbnb",
    careerUrl: "https://careers.airbnb.com",
    boards: [
    { board: "greenhouse", boardId: "airbnb" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Airbyte",
    careerUrl: "https://airbyte.com/careers",
    boards: [
    { board: "ashby", boardId: "airbyte" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Aircall",
    careerUrl: "https://aircall.io/careers",
    boards: [
    { board: "lever", boardId: "aircall" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Airtable",
    careerUrl: "https://www.airtable.com/careers",
    boards: [
    { board: "greenhouse", boardId: "airtable" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Amplitude",
    careerUrl: "https://amplitude.com/careers",
    boards: [
    { board: "greenhouse", boardId: "amplitude" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Anthropic",
    careerUrl: "https://www.anthropic.com/careers",
    boards: [
    { board: "greenhouse", boardId: "anthropic" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Asana",
    careerUrl: "https://asana.com/jobs",
    boards: [
    { board: "greenhouse", boardId: "asana" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Baseten",
    careerUrl: "https://www.baseten.co/careers",
    boards: [
    { board: "ashby", boardId: "baseten" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Betterment",
    careerUrl: "https://www.betterment.com/careers",
    boards: [
    { board: "greenhouse", boardId: "betterment" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Block",
    careerUrl: "https://block.xyz/careers",
    boards: [
    { board: "greenhouse", boardId: "block" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Brave",
    careerUrl: "https://brave.com/careers",
    boards: [
    { board: "greenhouse", boardId: "brave" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Braze",
    careerUrl: "https://www.braze.com/careers",
    boards: [
    { board: "greenhouse", boardId: "braze" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Brex",
    careerUrl: "https://www.brex.com/careers",
    boards: [
    { board: "greenhouse", boardId: "brex" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Chime",
    careerUrl: "https://www.chime.com/careers",
    boards: [
    { board: "greenhouse", boardId: "chime" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Cloudflare",
    careerUrl: "https://www.cloudflare.com/careers",
    boards: [
    { board: "greenhouse", boardId: "cloudflare" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Cloudinary",
    careerUrl: "https://cloudinary.com/careers",
    boards: [
    { board: "lever", boardId: "cloudinary" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Cockroach Labs",
    careerUrl: "https://www.cockroachlabs.com/careers",
    boards: [
    { board: "greenhouse", boardId: "cockroachlabs" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Coinbase",
    careerUrl: "https://www.coinbase.com/careers",
    boards: [
    { board: "greenhouse", boardId: "coinbase" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Databricks",
    careerUrl: "https://www.databricks.com/company/careers",
    boards: [
    { board: "greenhouse", boardId: "databricks" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Datadog",
    careerUrl: "https://www.datadoghq.com/careers",
    boards: [
    { board: "greenhouse", boardId: "datadog" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Discord",
    careerUrl: "https://discord.com/careers",
    boards: [
    { board: "greenhouse", boardId: "discord" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Dropbox",
    careerUrl: "https://www.dropbox.com/jobs",
    boards: [
    { board: "greenhouse", boardId: "dropbox" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Duolingo",
    careerUrl: "https://careers.duolingo.com",
    boards: [
    { board: "greenhouse", boardId: "duolingo" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Elastic",
    careerUrl: "https://www.elastic.co/careers",
    boards: [
    { board: "greenhouse", boardId: "elastic" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "ElevenLabs",
    careerUrl: "https://elevenlabs.io/careers",
    boards: [
    { board: "ashby", boardId: "elevenlabs" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Fastly",
    careerUrl: "https://www.fastly.com/careers",
    boards: [
    { board: "greenhouse", boardId: "fastly" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Figma",
    careerUrl: "https://www.figma.com/careers",
    boards: [
    { board: "greenhouse", boardId: "figma" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Finch",
    careerUrl: "https://finch.com/careers",
    boards: [
    { board: "ashby", boardId: "finch" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "GitLab",
    careerUrl: "https://about.gitlab.com/jobs",
    boards: [
    { board: "greenhouse", boardId: "gitlab" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "GoDaddy",
    careerUrl: "https://careers.godaddy.com",
    boards: [
    { board: "greenhouse", boardId: "godaddy" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Gopuff",
    careerUrl: "https://gopuff.com/careers",
    boards: [
    { board: "lever", boardId: "gopuff" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Gusto",
    careerUrl: "https://gusto.com/about/careers",
    boards: [
    { board: "greenhouse", boardId: "gusto" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Hex",
    careerUrl: "https://hex.tech/careers",
    boards: [
    { board: "ashby", boardId: "hex" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Instacart",
    careerUrl: "https://instacart.careers",
    boards: [
    { board: "greenhouse", boardId: "instacart" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Kalshi",
    careerUrl: "https://kalshi.com/careers",
    boards: [
    { board: "ashby", boardId: "kalshi" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Klaviyo",
    careerUrl: "https://www.klaviyo.com/careers",
    boards: [
    { board: "greenhouse", boardId: "klaviyo" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Knock",
    careerUrl: "https://knock.app/careers",
    boards: [
    { board: "ashby", boardId: "knock" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Linear",
    careerUrl: "https://linear.app/careers",
    boards: [
    { board: "ashby", boardId: "linear" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Metabase",
    careerUrl: "https://www.metabase.com/careers",
    boards: [
    { board: "lever", boardId: "metabase" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Midjourney",
    careerUrl: "https://www.midjourney.com/careers",
    boards: [
    { board: "ashby", boardId: "midjourney" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Mixpanel",
    careerUrl: "https://mixpanel.com/careers",
    boards: [
    { board: "greenhouse", boardId: "mixpanel" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Modal",
    careerUrl: "https://modal.com/careers",
    boards: [
    { board: "ashby", boardId: "modal" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "MongoDB",
    careerUrl: "https://www.mongodb.com/careers",
    boards: [
    { board: "greenhouse", boardId: "mongodb" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Monzo",
    careerUrl: "https://monzo.com/careers",
    boards: [
    { board: "greenhouse", boardId: "monzo" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Mozilla",
    careerUrl: "https://www.mozilla.org/careers",
    boards: [
    { board: "greenhouse", boardId: "mozilla" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "N26",
    careerUrl: "https://n26.com/en/careers",
    boards: [
    { board: "greenhouse", boardId: "n26" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Netlify",
    careerUrl: "https://www.netlify.com/careers",
    boards: [
    { board: "greenhouse", boardId: "netlify" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Okta",
    careerUrl: "https://www.okta.com/company/careers",
    boards: [
    { board: "greenhouse", boardId: "okta" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Outreach",
    careerUrl: "https://www.outreach.io/careers",
    boards: [
    { board: "lever", boardId: "outreach" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Parafin",
    careerUrl: "https://www.parafin.com/careers",
    boards: [
    { board: "ashby", boardId: "parafin" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Perplexity",
    careerUrl: "https://www.perplexity.ai/careers",
    boards: [
    { board: "ashby", boardId: "perplexity" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Pinecone",
    careerUrl: "https://www.pinecone.io/careers",
    boards: [
    { board: "ashby", boardId: "pinecone" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Pinterest",
    careerUrl: "https://www.pinterestcareers.com",
    boards: [
    { board: "greenhouse", boardId: "pinterest" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "PlanetScale",
    careerUrl: "https://planetscale.com/careers",
    boards: [
    { board: "greenhouse", boardId: "planetscale" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "PostHog",
    careerUrl: "https://posthog.com/careers",
    boards: [
    { board: "ashby", boardId: "posthog" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Postman",
    careerUrl: "https://www.postman.com/company/careers",
    boards: [
    { board: "greenhouse", boardId: "postman" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Ramp",
    careerUrl: "https://ramp.com/careers",
    boards: [
    { board: "ashby", boardId: "ramp" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Reddit",
    careerUrl: "https://www.redditinc.com/careers",
    boards: [
    { board: "greenhouse", boardId: "reddit" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Remote",
    careerUrl: "https://remote.com/careers",
    boards: [
    { board: "greenhouse", boardId: "remote" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Render",
    careerUrl: "https://render.com/careers",
    boards: [
    { board: "ashby", boardId: "render" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Replit",
    careerUrl: "https://replit.com/careers",
    boards: [
    { board: "ashby", boardId: "replit" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Resend",
    careerUrl: "https://resend.com/careers",
    boards: [
    { board: "ashby", boardId: "resend" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Ro",
    careerUrl: "https://ro.co/careers",
    boards: [
    { board: "lever", boardId: "ro" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Robinhood",
    careerUrl: "https://careers.robinhood.com",
    boards: [
    { board: "greenhouse", boardId: "robinhood" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Roblox",
    careerUrl: "https://careers.roblox.com",
    boards: [
    { board: "greenhouse", boardId: "roblox" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Rover",
    careerUrl: "https://www.rover.com/careers",
    boards: [
    { board: "lever", boardId: "rover" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Snowflake",
    careerUrl: "https://www.snowflake.com/careers",
    boards: [
    { board: "ashby", boardId: "snowflake" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "SoFi",
    careerUrl: "https://www.sofi.com/careers",
    boards: [
    { board: "greenhouse", boardId: "sofi" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Spotify",
    careerUrl: "https://www.lifeatspotify.com",
    boards: [
    { board: "lever", boardId: "spotify" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Squarespace",
    careerUrl: "https://www.squarespace.com/careers",
    boards: [
    { board: "greenhouse", boardId: "squarespace" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Stripe",
    careerUrl: "https://stripe.com/jobs",
    boards: [
    { board: "greenhouse", boardId: "stripe" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Supabase",
    careerUrl: "https://supabase.com/careers",
    boards: [
    { board: "ashby", boardId: "supabase" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Toast",
    careerUrl: "https://careers.toasttab.com",
    boards: [
    { board: "greenhouse", boardId: "toast" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Twilio",
    careerUrl: "https://www.twilio.com/company/jobs",
    boards: [
    { board: "greenhouse", boardId: "twilio" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Vercel",
    careerUrl: "https://vercel.com/careers",
    boards: [
    { board: "greenhouse", boardId: "vercel" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "WalkMe",
    careerUrl: "https://www.walkme.com/careers",
    boards: [
    { board: "lever", boardId: "walkme" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Weaviate",
    careerUrl: "https://weaviate.io/careers",
    boards: [
    { board: "ashby", boardId: "weaviate" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Webflow",
    careerUrl: "https://webflow.com/careers",
    boards: [
    { board: "greenhouse", boardId: "webflow" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Wikimedia",
    careerUrl: "https://wikimediafoundation.org/about/jobs",
    boards: [
    { board: "greenhouse", boardId: "wikimedia" },
    ],
    verifiedAt: "2026-08-14",
  },
  {
    name: "Wise",
    careerUrl: "https://www.wise.jobs",
    boards: [
    { board: "greenhouse", boardId: "wise" },
    ],
    verifiedAt: "2026-08-14",
  },
];
