/**
 * gen-blog.ts — generate src/generated/blog-content.ts from blog-content/*.md.
 *
 * Run: bun run scripts/gen-blog.ts   (also wired into build-vercel.sh/publish.sh)
 *
 * Why a generator instead of Vite `?raw` imports: the Vercel SSR bundle is made
 * with `bun build` (CLI), which does NOT resolve `?raw` — a plain generated TS
 * module works in both the vite build and the bun SSR bundle.
 *
 * Frontmatter parse rules (lead's spec):
 *   - split on the FIRST colon for description/keywords (values keep later colons)
 *   - only keywords splits on commas
 *   - readingTimeMinutes is an int; date is YYYY-MM-DD
 * The trailing "## Try it" section duplicates ctaTitle/ctaBody — it is dropped
 * here; routes render the CTA box from frontmatter instead (consistent).
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SRC = join(import.meta.dirname, "..", "blog-content");
const OUT = join(import.meta.dirname, "..", "src", "generated", "blog-content.ts");

interface RawPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  keywords: string[];
  readingTimeMinutes: number;
  ctaTitle: string;
  ctaBody: string;
  bodyMd: string;
}

function parseFrontmatter(raw: string): { fm: Record<string, string>; body: string } {
  const lines = raw.split("\n");
  if (lines[0]?.trim() !== "---") throw new Error("missing leading frontmatter delimiter");
  const fm: Record<string, string> = {};
  let i = 1;
  for (; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === "---") break;
    const idx = line.indexOf(":");
    if (idx < 0) continue;
    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 1).trim();
    if (key) fm[key] = value;
  }
  return { fm, body: lines.slice(i + 1).join("\n") };
}

/** Drop the trailing "## Try it" section (it duplicates the frontmatter CTA). */
function stripTryIt(body: string): string {
  const lines = body.split("\n");
  const idx = lines.findIndex((l) => /^#{2,3}\s+Try it\s*$/.test(l.trim()));
  if (idx < 0) return body.trim();
  return lines.slice(0, idx).join("\n").trim();
}

function escTemplate(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function build(): void {
  const files = readdirSync(SRC).filter((f) => f.endsWith(".md")).sort();
  if (files.length === 0) throw new Error(`no .md files in ${SRC}`);
  const posts: RawPost[] = files.map((f) => {
    const raw = readFileSync(join(SRC, f), "utf8");
    const { fm, body } = parseFrontmatter(raw);
    const keywords = (fm.keywords ?? "").split(",").map((k) => k.trim()).filter(Boolean);
    const minutes = Number.parseInt(fm.readingTimeMinutes ?? "", 10);
    const post: RawPost = {
      slug: fm.slug ?? f.replace(/\.md$/, ""),
      title: fm.title ?? f.replace(/\.md$/, ""),
      description: fm.description ?? "",
      date: fm.date ?? "",
      keywords,
      readingTimeMinutes: Number.isFinite(minutes) && minutes > 0 ? minutes : 5,
      ctaTitle: fm.ctaTitle ?? "",
      ctaBody: fm.ctaBody ?? "",
      bodyMd: stripTryIt(body),
    };
    if (!post.title || !post.description || !post.date) {
      throw new Error(`post ${f}: missing title/description/date in frontmatter`);
    }
    return post;
  });

  // newest-first by date; stable tie-break by slug so output is deterministic.
  posts.sort((a, b) => (a.date === b.date ? a.slug.localeCompare(b.slug) : b.date.localeCompare(a.date)));

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by scripts/gen-blog.ts — do not edit by hand.");
  lines.push("// Run `bun run scripts/gen-blog.ts` after editing blog-content/*.md.");
  lines.push("");
  lines.push("export interface BlogPost {");
  lines.push("  slug: string;");
  lines.push("  title: string;");
  lines.push("  description: string;");
  lines.push("  date: string; // YYYY-MM-DD");
  lines.push("  keywords: string[];");
  lines.push("  readingTimeMinutes: number;");
  lines.push("  ctaTitle: string;");
  lines.push("  ctaBody: string;");
  lines.push("  bodyMd: string; // markdown body without the trailing \"## Try it\" section");
  lines.push("}");
  lines.push("");
  lines.push("export const BLOG_POSTS: BlogPost[] = [");
  for (const p of posts) {
    lines.push("  {");
    lines.push(`    slug: ${JSON.stringify(p.slug)},`);
    lines.push(`    title: ${JSON.stringify(p.title)},`);
    lines.push(`    description: ${JSON.stringify(p.description)},`);
    lines.push(`    date: ${JSON.stringify(p.date)},`);
    lines.push(`    keywords: ${JSON.stringify(p.keywords)},`);
    lines.push(`    readingTimeMinutes: ${p.readingTimeMinutes},`);
    lines.push(`    ctaTitle: ${JSON.stringify(p.ctaTitle)},`);
    lines.push(`    ctaBody: ${JSON.stringify(p.ctaBody)},`);
    lines.push(`    bodyMd: \`${escTemplate(p.bodyMd)}\`,`);
    lines.push("  },");
  }
  lines.push("];");
  lines.push("");
  lines.push("export function postBySlug(slug: string): BlogPost | undefined {");
  lines.push("  return BLOG_POSTS.find((p) => p.slug === slug);");
  lines.push("}");
  lines.push("");

  mkdirSync(join(import.meta.dirname, "..", "src", "generated"), { recursive: true });
  writeFileSync(OUT, lines.join("\n"));
  console.log(`gen-blog: wrote ${OUT} (${posts.length} posts)`);
}

build();
